name: SoulsSMP
version: '${version}'

main: net.ape.soulssmp.SoulsSMP
api-version: '1.21.11'
load: STARTUP

authors: [ApeTakeOver, random_revilo]

commands:
  soul:
    description: Access your Soul abilities
    usage: /soul <ability>
  soultest:
    description: TEMP - force-assign a soul and mana for testing
    usage: /soultest <void|blood|echo>